NEXT_PUBLIC_API_BASE_URL: https://api.callsomeone.org
NEXT_PUBLIC_FIREBASE_API_KEY: AIzaSyD19PzrYQ-dtRNvLi81fqbP3TFgObXFej8
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ear-thabhelo.firebaseapp.com
NEXT_PUBLIC_FIREBASE_PROJECT_ID: ear-thabhelo
NEXT_PUBLIC_FIREBASE_APP_ID: 1:963565155466:web:9e7f80d2badfcb96a4a973
NEXT_PUBLIC_BOOKING_URL: https://calendar.google.com/calendar/appointments/schedules/AcZssZ1M0OUWwW_1dvgd7rLXW_1aR5uSPUZWcI-geJxVJ9TMOS43x0AVwvZ5gGYHY2vL97dbg80G28Fh
